# Generated by Django 5.1.6 on 2025-03-04 14:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_add_shipping_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='free_shipping',
            field=models.BooleanField(default=False, help_text='Whether shipping costs are included in the product price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height in inches (in)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01, message='Height must be greater than 0')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Length in inches (in)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01, message='Length must be greater than 0')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='requires_shipping',
            field=models.BooleanField(default=True, help_text='Whether this product needs to be shipped. Digital products should set this to False.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in pounds (lb)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01, message='Weight must be greater than 0')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Width in inches (in)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01, message='Width must be greater than 0')]),
        ),
    ]
